# Generated by Django 5.1.4 on 2026-04-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon identifier", max_length=50
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "content_category",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OfficialExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Januar"), (8, "August")]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "pass_score",
                    models.PositiveSmallIntegerField(
                        default=32, help_text="Minimum correct answers to pass"
                    ),
                ),
                ("total_time_minutes", models.PositiveSmallIntegerField(default=45)),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, help_text="Accessible on free tier"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "content_official_exam",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Let"),
                            ("medium", "Mellem"),
                            ("hard", "Svær"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(help_text="Shown after the user answers"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_free",
                    models.BooleanField(
                        default=False,
                        help_text="Available without a premium subscription",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="content.category",
                    ),
                ),
            ],
            options={
                "db_table": "content_question",
                "ordering": ["category", "id"],
            },
        ),
        migrations.CreateModel(
            name="OfficialExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.officialexam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="content.question",
                    ),
                ),
            ],
            options={
                "db_table": "content_official_exam_question",
                "ordering": ["order"],
                "unique_together": {("exam", "order")},
            },
        ),
        migrations.AddField(
            model_name="officialexam",
            name="questions",
            field=models.ManyToManyField(
                related_name="official_exams",
                through="content.OfficialExamQuestion",
                to="content.question",
            ),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="content.question",
                    ),
                ),
            ],
            options={
                "db_table": "content_choice",
                "ordering": ["order"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="officialexam",
            unique_together={("year", "month")},
        ),
    ]
