# Generated by Django 5.1.4 on 2026-07-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="option_letter",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name="officialexam",
            name="season",
            field=models.CharField(
                blank=True,
                help_text="'sommer' or 'vinter' from official naming",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_sentences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="historical_note_sentences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="original_correct_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Gyldig"),
                    ("updated", "Opdateret"),
                    ("udgaaet", "Udgået"),
                ],
                default="valid",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="officialexam",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="officialexam",
            name="month",
            field=models.PositiveSmallIntegerField(
                help_text="Numeric month (1=Januar, 8=August, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="officialexam",
            name="pass_score",
            field=models.PositiveSmallIntegerField(default=32),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="content.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "subcategories",
                "db_table": "content_subcategory",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="content.subcategory",
            ),
        ),
    ]
