# Generated by Django 5.1.4 on 2026-04-28 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stripe_price_id", models.CharField(max_length=100, unique=True)),
                ("price_dkk", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("month", "Månedlig"),
                            ("year", "Årlig"),
                            ("one_time", "Engangsbeløb"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "payments_subscription_plan",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=200, unique=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("amount_dkk", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Afventer"),
                            ("succeeded", "Gennemført"),
                            ("failed", "Fejlet"),
                            ("refunded", "Refunderet"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
    ]
